import Head from 'next/head'
import Image from 'next/image'
import Card from "./components/card"
import styles from '../styles/Home.module.css'
import useSWR, { SWRConfig } from "swr";


export default function Home() {

  const fetcher = (url) => fetch(url).then((res) => res.json()); //intit SWR


  const { data: userData, error: userError } = useSWR( //fetch github users
      "https://api.github.com/users",
      fetcher
  );

  const { data: textData, error: textError } = useSWR( //fetch random text
      "https://jsonplaceholder.typicode.com/posts",
      fetcher
  );

  if (userError,textError) return <div>failed to load</div> //swr error handleing
  if (!userData,!textData) return <div>loading...</div>

  return (  
    <div>

      <Head>
            <title>Cub Digital Task</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>

      {userData.map((_, key) => <Card  title={textData[key].title} body={textData[key].body} img ={"https://picsum.photos/seed/picsum/300/300"} url={userData[key].avatar_url} login={userData[key].login}></Card>) }
      
    </div>    
    
    
    )
  
}
